apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "test-pod"
  namespace: "default"
  labels:
    app: "test-pod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "test-pod"
  template:
    metadata:
      labels:
        app: "test-pod"
    spec:
      containers:
      - name: "my-exp-1"
        image: "bistrulli/my_exp:test_pod"
        imagePullPolicy: "Always"