apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tier1-pod"
  namespace: "default"
  labels:
    app: "tier1-pod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tier1-pod"
  template:
    metadata:
      labels:
        app: "tier1-pod"
    spec:
      containers:
      - name: "tier1-pod"
        image: "bistrulli/tier1:0.7"
        imagePullPolicy: "Always"
        command: ["java","-Xmx4G","-jar","tier1-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
        #resources:
          #limits:
            #cpu: "25000m"
