apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tier2-pod"
  namespace: "default"
  labels:
    app: "tier2-pod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tier2-pod"
  template:
    metadata:
      labels:
        app: "tier2-pod"
    spec:
      containers:
      - name: "tier2-pod"
        image: "bistrulli/tier2:gke_0.7"
        imagePullPolicy: "Always"
        command: ["sleep", "1d"]
        #command: ["java","-Xmx6G", "-Xms6G","-Djava.compiler=NONE","-jar","tier2-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor","--cgv2","0"]
        #resources:
          #limits:
            #cpu: "25000m"