apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "tier2-pod"
  namespace: "default"
  labels:
    app: "tier2-pod"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "tier2-pod"
  template:
    metadata:
      labels:
        app: "tier2-pod"
    spec:
      containers:
      - name: "tier2-pod"
        image: "bistrulli/tier2:0.2"
        imagePullPolicy: "Always"
        command: ["java","-Xmx4G","-jar","tier2-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
        resources:
          limits:
            cpu: "25000m"