version: "3.9"
services:
  monitor:
    image: "memcached:1.6.12"
    container_name: monitor-cnt
    #command: ["redis-server","/etc/redis-no-persistence.conf"]
    #command: ["redis-server","--save","--dbfilename","''","--appendonly","no","--appendfsync","no","--protected-mode","no"]
    ports:
      - "11211:11211"
  tier2:
    container_name: tier2-cnt
    image: "bistrulli/tier2:0.7"
    depends_on:
      - monitor
    command: ["java","-Xmx4G","-jar","tier2-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
  tier1:
    container_name: tier1-cnt
    image: "bistrulli/tier1:0.7" 
    depends_on:
      - tier2
    command: ["java","-Xmx4G","-jar","tier1-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
    ports:
      - "3000:3000"