version: "2.4"
services:
  monitor:
    image: "bistrulli/my_exp:my_redis_srv"
    #command: ["redis-server","/etc/redis-no-persistence.conf"]
    command: ["redis-server","--save","--dbfilename","''","--appendonly","no","--appendfsync","no","--protected-mode","no"]
    cpuset: "0-1"
    ports:
      - "6379:6379"
  tier2:
    container_name: tier2-cnt
    image: "bistrulli/tier2:0.5"
    cpuset: "2-31"
    depends_on:
      - monitor
    command: ["java","-Xmx4G","-jar","tier2-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
  tier1:
    container_name: tier1-cnt
    image: "bistrulli/tier1:0.5"
    cpuset: "2-31" 
    depends_on:
      - monitor
      - tier2
    command: ["java","-Xmx4G","-jar","tier1-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","0","--jedisHost","monitor"]
    ports:
      - "3000:3000"