version: "3.9"
services:
  monitor:
    image: "bistrulli/my_exp:my_redis_srv"
  tier2:
    image: "bistrulli/tier2:0.1"
    depends_on:
      - monitor
    command: ["java","-Xmx4G","-jar","tier2-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","1","--jedisHost","monitor"]
  tier1:
    image: "bistrulli/tier1:0.1"
    depends_on:
      - monitor
      - tier2
    command: ["java","-Xmx4G","-jar","tier1-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--cpuEmu","1","--jedisHost","monitor"]
  client:
    image: "bistrulli/client:0.1"
    depends_on:
      - monitor
      - tier2
      - tier1
    command: ["java","-Xmx4G","-jar","client-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--initPop","100",\
                  ,"--queues",'["think", "e1_bl", "e1_ex", "t1_hw", "e2_bl", "e2_ex", "t2_hw"]',"--jedisHost","monitor"]
  controller:
    image: "bistrulli/controller:0.1"
    depends_on:
      - monitor
      - tier2
      - tier1
    