apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "client"
  namespace: "default"
  labels:
    app: "client"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "client-pod"
  template:
    metadata:
      labels:
        app: "client-pod"
    spec:
      containers:
      - name: "client-pod"
        image: "bistrulli/client:gke_0.7"
        imagePullPolicy: "Always"
        command: ["sleep", "1d"]
#        command: ["java",\
#                  "-Xmx6G", "-Xms6G",\
#                  "-jar","client-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--initPop","40",\
#                  "--sim","1","--queues",'["think", "e1_bl", "e1_ex", "t1_hw", "e2_bl", "e2_ex", "t2_hw"]',\
#                  "--jedisHost","monitor","--tier1Host","tier1"]
                  