apiVersion: "apps/v1"
kind: "Deployment"
metadata:
  name: "client"
  namespace: "default"
  labels:
    app: "client"
spec:
  replicas: 1
  selector:
    matchLabels:
      app: "client-pod"
  template:
    metadata:
      labels:
        app: "client-pod"
    spec:
      containers:
      - name: "client-pod"
        image: "bistrulli/client:gke_0.4"
        imagePullPolicy: "Always"
        command: ["java","-Xmx4G","-jar","client-0.0.1-SNAPSHOT-jar-with-dependencies.jar","--initPop","40",\
                  ,"--queues",'["think", "e1_bl", "e1_ex", "t1_hw", "e2_bl", "e2_ex", "t2_hw"]',"--jedisHost","monitor","--tier1Host","tier1"]